<a href="https://colab.research.google.com/github/SolbiChoi/learn_python/blob/master/python_language.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.5'

In [70]:
def onehotcylinder(cylinders):
  if cylinders == 3:
    cylinder = np.array([1,0,0,0,0])
  elif cylinders == 4:
    cylinder = np.array([0,1,0,0,0])
  elif cylinders == 5:
    cylinder = np.array([0,1,0,0,0])
  elif cylinders == 6:
    cylinder = np.array([0,0,1,0,0])
  else:
    cylinder = np.array([0,0,0,1,0])
  return cylinder

In [72]:
displacement = 307.0
horsepower = 130.0
weight = 3504.0
accle = 12.0
cylinders = 8
origin = 1

# if cylinder = 8, origon = 1 -> onehot encoding

x_continuous = np.array([displacement,horsepower,weight,accle])
# cylinder = np.array([0,0,0,0,1])
cylinder = onehotcylinder(cylinders)
org = np.array([1,0,0])

In [73]:
# np.concatenate((a, b), axis=None)
result = np.concatenate((x_continuous, cylinder, org), axis=None)
result.shape, result

((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 1.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

In [74]:
# result.reshape(1,12) 
result = result.reshape(-1, result.size)
result, result.shape

(array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 1.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]),
 (1, 12))

In [41]:
result.size
result

array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 1.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]])

## function 이해

In [42]:
21 + 14

35

In [43]:
32 + 45

77

In [45]:
def sum():
  first = 21
  second = 14
  result = first + second
  return result

In [46]:
sum()

35

In [60]:
def sum(f01, s02):
  first = s02
  second = f01
  result = first + second
  return result, second, first

In [61]:
r01, r02, r03 = sum(4,5)
print(r01, r02)

9 4


In [50]:
def mul(a1,a2,a3):
  first = a1
  second = a2
  third = a3
  result = first*second*third
  return result

In [51]:
mul(21,32,2), mul(31,63,41)

(1344, 80073)

In [65]:
def diffparam(*var_list,**var_dict):
  print(var_dict)
  result01 = len(var_list)
  return result01

In [66]:
diffparam(1,2,3,a=2,b=3)

{'a': 2, 'b': 3}


3

In [67]:
diffparam(1,2,3,4,5,a=2,b=3,c=4)

{'a': 2, 'b': 3, 'c': 4}


5